Spree::ActiveShipping::Config[:origin_country] = "USA"
Spree::ActiveShipping::Config[:origin_city] = "Muncie"
Spree::ActiveShipping::Config[:origin_state] = "IN"
Spree::ActiveShipping::Config[:origin_zip] = "47304"
Spree::ActiveShipping::Config[:ups_login] = ENV["UPS_LOGIN"] || "dbwinger"
Spree::ActiveShipping::Config[:ups_password] = ENV["UPS_PASSWORD"] || "awcAWC123"
Spree::ActiveShipping::Config[:ups_key] = ENV["UPS_KEY"] || "4CC1776376AA84B6"
Spree::ActiveShipping::Config[:shipper_number] = ENV["SHIPPER_NUMBER"] || "Y8749W"
Spree::ActiveShipping::Config[:usps_login] = ""
Spree::ActiveShipping::Config[:handling_fee] = "100"

